### ISSUE TITLE
thread 'main' panicked at 'Storage Error: StorageInconsistentState("Trie node missing") in syncing

### ISSUE THREAD

**Issue by sl-he** [near/nearup#63] opened 2020-05-25 10:13 UTC
May 25 10:08:27.236  INFO stats: # 5772835 Downloading headers 97% -/55 16/13/40 peers ⬇ 365.9kiB/s ⬆ 14.1kiB/s 0.00 bps 0 gas/s CPU: 90%, Mem: 590.8 MiB
May 25 10:08:40.644  INFO stats: # 5772835 Downloading headers 98% -/55 15/13/40 peers ⬇ 379.0kiB/s ⬆ 17.8kiB/s 0.00 bps 0 gas/s CPU: 85%, Mem: 591.0 MiB
May 25 10:08:56.113  INFO stats: # 5772835 Downloading headers 99% -/55 15/13/40 peers ⬇ 383.0kiB/s ⬆ 18.7kiB/s 0.00 bps 0 gas/s CPU: 84%, Mem: 591.8 MiB
May 25 10:09:07.718  INFO stats: # 5772835 Downloading headers 99% -/55 15/13/40 peers ⬇ 377.1kiB/s ⬆ 17.7kiB/s 0.00 bps 0 gas/s CPU: 109%, Mem: 593.6 MiB
May 25 10:09:10.257  INFO telemetry: Telemetry data could not be sent due to: Failed to connect to host: Timeout out while establishing connection
May 25 10:09:38.108  INFO stats: State [0: header] -/55 15/13/40 peers ⬇ 413.9kiB/s ⬆ 16.7kiB/s 0.00 bps 0 gas/s CPU: 106%, Mem: 595.2 MiB
May 25 10:09:48.111  INFO stats: State [0: parts] -/55 15/13/40 peers ⬇ 578.6kiB/s ⬆ 15.8kiB/s 0.00 bps 0 gas/s CPU: 40%, Mem: 607.1 MiB
May 25 10:09:49.313  WARN sync: State sync didn't download the state for shard 0 in 10 seconds, sending StateRequest again
May 25 10:09:58.114  INFO stats: State [0: parts] -/55 15/13/40 peers ⬇ 650.5kiB/s ⬆ 16.2kiB/s 0.00 bps 0 gas/s CPU: 36%, Mem: 614.3 MiB
May 25 10:09:59.317  WARN sync: State sync didn't download the state for shard 0 in 10 seconds, sending StateRequest again
May 25 10:10:08.118  INFO stats: State [0: parts] -/55 15/13/40 peers ⬇ 610.5kiB/s ⬆ 17.7kiB/s 0.00 bps 0 gas/s CPU: 29%, Mem: 615.1 MiB
May 25 10:10:09.326  WARN sync: State sync didn't download the state for shard 0 in 10 seconds, sending StateRequest again
thread 'main' panicked at 'Storage Error: StorageInconsistentState("Trie node missing")
 Cause: Unknown
 Backtrace:    0: failure::backtrace::Backtrace::new
   1: neard::runtime::NightshadeRuntime::process_state_update
   2: <neard::runtime::NightshadeRuntime as near_chain::types::RuntimeAdapter>::apply_transactions_with_optional_storage_proof
   3: near_chain::types::RuntimeAdapter::apply_transactions
   4: near_chain::chain::ChainUpdate::apply_chunks
   5: near_chain::chain::Chain::process_block_single
   6: near_client::client::Client::process_partial_encoded_chunk
   7: <near_client::client_actor::ClientActor as actix::handler::Handler<near_network::types::NetworkClientMessages>>::handle
   8: <actix::address::envelope::SyncEnvelopeProxy<A,M> as actix::address::envelope::EnvelopeProxy>::handle
   9: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
  10: tokio::runtime::task::raw::poll
  11: <std::future::GenFuture<T> as core::future::future::Future>::poll
  12: actix_rt::runtime::Runtime::block_on
  13: near::main
  14: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/rt.rs:52
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/sys_common/backtrace.rs:130
  15: main
  16: __libc_start_main
  17: _start
', neard/src/runtime.rs:901:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1427
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: near_actix_utils::init_stop_on_panic::{{closure}}::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: rust_begin_unwind
             at src/libstd/panicking.rs:419
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:373
  14: <neard::runtime::NightshadeRuntime as near_chain::types::RuntimeAdapter>::apply_transactions_with_optional_storage_proof
  15: near_chain::types::RuntimeAdapter::apply_transactions
  16: near_chain::chain::ChainUpdate::apply_chunks
  17: near_chain::chain::Chain::process_block_single
  18: near_client::client::Client::process_partial_encoded_chunk
  19: <near_client::client_actor::ClientActor as actix::handler::Handler<near_network::types::NetworkClientMessages>>::handle
  20: <actix::address::envelope::SyncEnvelopeProxy<A,M> as actix::address::envelope::EnvelopeProxy>::handle
  21: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
  22: tokio::runtime::task::raw::poll
  23: <std::future::GenFuture<T> as core::future::future::Future>::poll
  24: actix_rt::runtime::Runtime::block_on
  25: near::main
  26: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at src/libstd/rt.rs:52
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
May 25 10:10:11.696 ERROR network: Received error sending message to client: Mailbox has closed for Some(ed25519:GkDv7nSMS3xcqA45cpMvFmfV1o4fRF6zYo1JRR6mNqg5@35.226.250.82:24567)
May 25 10:10:11.696 ERROR network: Received error sending message to client: Mailbox has closed for Some(ed25519:GkDv7nSMS3xcqA45cpMvFmfV1o4fRF6zYo1JRR6mNqg5@35.226.250.82:24567)
May 25 10:10:11.696 ERROR network: Received error sending message to client: Mailbox has closed for Some(ed25519:GkDv7nSMS3xcqA45cpMvFmfV1o4fRF6zYo1JRR6mNqg5@35.226.250.82:24567)
May 25 10:10:11.696 ERROR network: Received error sending message to client: Mailbox has closed for Some(ed25519:GkDv7nSMS3xcqA45cpMvFmfV1o4fRF6zYo1JRR6mNqg5@35.226.250.82:24567)
May 25 10:10:11.700 ERROR network: Received error sending message to client: Mailbox has closed for Some(ed25519:GPJuqYzkkbxZo1HQwgYLQDyQdK4EFGx8kdXGGUFb4Zie@78.46.229.112:24567)
May 25 10:10:11.700 ERROR network: Received error sending message to client: Mailbox has closed for Some(ed25519:GPJuqYzkkbxZo1HQwgYLQDyQdK4EFGx8kdXGGUFb4Zie@78.46.229.112:24567)
May 25 10:10:11.700 ERROR network: Received error sending message to client: Mailbox has closed for Some(ed25519:AVPhuz3f9JptJBWJR3rCGwMauH5uXhLchPVTY1NGq4bS@185.144.83.146:24567)
May 25 10:10:11.700 ERROR network: Received error sending message to client: Mailbox has closed for Some(ed25519:AVPhuz3f9JptJBWJR3rCGwMauH5uXhLchPVTY1NGq4bS@185.144.83.146:24567)
May 25 10:10:11.700 ERROR network: Received error sending message to client: Mailbox has closed for Some(ed25519:AVPhuz3f9JptJBWJR3rCGwMauH5uXhLchPVTY1NGq4bS@185.144.83.146:24567)
May 25 10:10:11.700 ERROR network: Received error sending message to client: Mailbox has closed for Some(ed25519:AVPhuz3f9JptJBWJR3rCGwMauH5uXhLchPVTY1NGq4bS@185.144.83.146:24567)
May 25 10:10:11.700 ERROR network: Received error sending message to client: Mailbox has closed for Some(ed25519:AVPhuz3f9JptJBWJR3rCGwMauH5uXhLchPVTY1NGq4bS@185.144.83.146:24567)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Non-zero exit code: 1" }', neard/src/../src/main.rs:201:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1427
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: near_actix_utils::init_stop_on_panic::{{closure}}::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: rust_begin_unwind
             at src/libstd/panicking.rs:419
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  14: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  15: near::main
  16: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at src/libstd/rt.rs:52
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by bowenwang1996** [comment] 2020-05-25 14:07
duplicate of https://github.com/nearprotocol/nearcore/issues/2695

**Closed as completed by bowenwang1996** 2020-05-25 14:07 UTC
